// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaBEUg6AjO4duqkBE-bEX-T1HgKSzZYw4',
    appId: '1:757172875687:web:067748d9a35d26a2978682',
    messagingSenderId: '757172875687',
    projectId: 'cloudfunction-39ae2',
    authDomain: 'cloudfunction-39ae2.firebaseapp.com',
    storageBucket: 'cloudfunction-39ae2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-qxMa2BYjSXg8nBsyQtd8jvQi36M31eY',
    appId: '1:757172875687:android:25a8f6df27758317978682',
    messagingSenderId: '757172875687',
    projectId: 'cloudfunction-39ae2',
    storageBucket: 'cloudfunction-39ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9r_OJcUstuWgYgRMuR0H9qsX1vRm5qZA',
    appId: '1:757172875687:ios:aaf97fd5abd3b93b978682',
    messagingSenderId: '757172875687',
    projectId: 'cloudfunction-39ae2',
    storageBucket: 'cloudfunction-39ae2.appspot.com',
    iosClientId: '757172875687-bag09qadaj490gquv2t1actmf6uc556a.apps.googleusercontent.com',
    iosBundleId: 'com.example.adventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9r_OJcUstuWgYgRMuR0H9qsX1vRm5qZA',
    appId: '1:757172875687:ios:aaf97fd5abd3b93b978682',
    messagingSenderId: '757172875687',
    projectId: 'cloudfunction-39ae2',
    storageBucket: 'cloudfunction-39ae2.appspot.com',
    iosClientId: '757172875687-bag09qadaj490gquv2t1actmf6uc556a.apps.googleusercontent.com',
    iosBundleId: 'com.example.adventure',
  );
}
